packages:
    - packages/**
    - packages/ide/**
    - samples/**
catalog:
    kysely: ^0.27.6
    zod: ^3.25.67
    prisma: ^6.0.0
    langium: 3.5.0
    langium-cli: 3.5.0
    ts-pattern: ^5.7.1
    typescript: ^5.0.0
