name: Bump Version

on:
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    bump-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: dev

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10.12.1

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Bump version
              run: pnpm run bump-version

            - name: Create PR
              uses: peter-evans/create-pull-request@v7
              with:
                  commit-message: 'chore: bump version'
                  title: '[CI] Bump version'
                  body: Automated changes for bumping version
                  branch: chore/ci-bump-version
                  branch-suffix: timestamp
